

WindowManager:
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: 0, 0
            size: self.size

<GameScreen>:

<Cell>:
    canvas:
        Color:
            rgba: self.color
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: (0.4, 0.4, 0.4, 1)
        Line:
            rectangle: (self.pos[0], self.pos[1], self.size[0], self.size[1])
            width: 2